services:
  - type: web
    name: crawl4ai-service
    env: node
    buildCommand: npm --prefix ./server install
    startCommand: npm --prefix ./server start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true